# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Continuos integration for Identitas

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
        
    - name: Create keys for token service
      run: |
        openssl genpkey -out app.key -algorithm RSA -pkeyopt rsa_keygen_bits:2048
        openssl rsa -in app.key -outform PEM -pubout -out app.pub
        cp app.* ./src/it/resources/
        cp app.* ./src/main/resources/

    - name: Build with Maven
      run: mvn -B clean verify --file pom.xml
      
    - name: Code coverage @Codecov
      uses: codecov/codecov-action@v2.1.0
      with:
        token: ${{secrets.CODECOV_TOKEN}}
        
